format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$python\
$go\
$docker\
$terraform\
$kubernetes\
$gcloud\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = false

[hostname]
ssh_symbol = 'üåê'
style = 'bold blue'
format = '[${ssh_symbol}${hostname} ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = '[‚á°${count}](bright-cyan)'
diverged = '[‚áï‚á°${ahead_count}‚á£${behind_count}](bright-purple)'
behind = '[‚á£${count}](bright-red)'
staged = '[+\($count\)](bright-green)'

[fill]
symbol = ' '

[directory]
style = 'bold fg:dark_blue'
truncation_length = 5
truncate_to_repo = false

[python]
symbol = 'ÓòÜ '
style = 'bold yellow'
format = '[${symbol}python (${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = false
pyenv_prefix = 'uv '
detect_extensions = ['py']
version_format = 'v${raw}'

[kubernetes]
disabled = true
symbol = 'Û±Éæ '
style = 'cyan bold'
format = '[$symbol$context( \($namespace\))]($style)'

[gcloud]
symbol = 'Û±á∂ '
style = 'bold blue'
format = '[${symbol} ${account}(@$domain) (\($project\) )]($style)'

[cmd_duration]
min_time = 1_000
style = 'bold red'
format = 'in [$duration]($style) '

[time]
disabled = false
style = 'bold green'
format = ' [$time]($style)'
time_format = '%I:%M:%S%p'
